FROM node:18-alpine

WORKDIR /usr/app/test-task
ENV NODE_ENV=production

COPY tsconfig.json package.json package-lock.json ./
RUN npm ci

COPY . ./
RUN npm run build

ENTRYPOINT ["npm", "run", "start:prod"]